### ISSUE TITLE
Separate the Service Locator dependency in to its own feature

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/com.realitytoolkit.core#1]
# Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

The Service Locator is a core part that is consumed by the Reality Toolkit but it is useful in itself to other Unity projects without the overhead of the Reality Toolkit itself.
Several projects have been noted to be consuming all of the core of the Toolkit, just to use the Service Locator feature.

## How would you classify your suggestion

- Architecture / Services

## Describe the solution you'd like

The Service Locator functionality itself should be broken out in to it's own separate project and the Reality Toolkit core project updated to use this as a dependency.

This would greatly reduce the impacts for customers only using the service locator feature.

Additionally, the following requirements were also identified:

* Requirement for an Initialise call to run in the editor (currently supported)
* Requirement for an Initialise call to ONLY run in play mode - Effectively the Awake call the Initialise functions uses but only for when a project is playing (suggestion is to add a bool to the "Initialize" call when awake is called, default will be false which is the first/existing behaviour)
* Requirement to add a Start method replicator - Start call for services

## Repository Location

- https://github.com/realitycollective/com.realitytoolkit.service-framework

**Comment by FejZa** [comment]
I disagree with adding a separate `InitialiseOnPlay` call to the service definition. It bloats the interface unnecessarily. Why not have the existing `Initialize` API have a bool paramter `Initialize(bool isPlaying)` e.g.

**Comment by FejZa** [comment]
Regarding the `Start` replica, that's a good thought. I guess it depends on whether we are looking to have services replicate a MonoBehaviour fully.

**Comment by SimonDarksideJ** [comment]
> I disagree with adding a separate `InitialiseOnPlay` call to the service definition. It bloats the interface unnecessarily. Why not have the existing `Initialize` API have a bool paramter `Initialize(bool isPlaying)` e.g.

Agreed, updated the spec to relate that feedback
