### ISSUE TITLE
Package Installer updates

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitytoolkit.core#72]
# Packages

## Pending
- [ ] https://github.com/realitycollective/com.realitytoolkit.upm.template
- [ ] https://github.com/realitycollective/com.realitytoolkit.locomotion
- [ ] https://github.com/realitycollective/com.realitytoolkit.spatial-persistence.asa
- [ ] https://github.com/realitycollective/com.realitytoolkit.windows.xr
- [ ] https://github.com/realitycollective/com.realitytoolkit.interaction-sdk
- [ ] https://github.com/realitycollective/com.realitycollective.webrtc
- [ ] https://github.com/realitycollective/com.realitycollective.photon

## Completed
- [X] https://github.com/realitycollective/com.realitytoolkit.pico
- [X] https://github.com/realitycollective/com.realitytoolkit.devicesimulation
- [X] https://github.com/realitycollective/com.realitycollective.service-framework
- [X] https://github.com/realitycollective/com.realitytoolkit.core
- [X] https://github.com/realitycollective/com.realitytoolkit.spatial-persistence
- [X] https://github.com/realitycollective/com.realitytoolkit.devtools
- [X] https://github.com/realitycollective/com.realitytoolkit.metaplatform
- [X] https://github.com/realitycollective/com.realitytoolkit.camera

## Not Applicable
- https://github.com/realitycollective/com.realitycollective.utilities
- https://github.com/realitycollective/com.realitycollective.buildtools

**Comment by FejZa** [comment]
Other packages will be updates once they are actually more than just empty stubs

**Comment by SimonDarksideJ** [comment]
Could we list here what the required changes are so anyone can pick them up, for instance, I'm hoping to finalise the ASA package soon @FejZa .

From what I can ascertain from the Spatial-Persistence package, it is as follows:
* New PackageInstaller script
* New Modules Installer script
* Rename and update package finder
* Remove old package inspector

Does that round right?
(https://github.com/realitycollective/com.realitytoolkit.spatial-persistence/pull/12/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
